### ISSUE TITLE
WSL 

### ISSUE THREAD

**Issue by likh31** [MicrosoftDocs/WSL#2051]
### Type of issue

Other (describe below)

### Feedback

.

### Page URL

https://learn.microsoft.com/en-us/windows/wsl/install

### Content source URL

https://github.com/MicrosoftDocs/wsl/blob/main/WSL/install.md

### Author

@mattwojo

### Document Id

7ed8fb81-5b8f-4d56-7b89-bf600ce6080a
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/WSL/issues/2050
- [ ] https://github.com/MicrosoftDocs/WSL/issues/1180
- [ ] https://github.com/MicrosoftDocs/WSL/issues/2049
- [ ] https://github.com/MicrosoftDocs/WSL/issues/2047
- [ ] https://github.com/MicrosoftDocs/WSL/issues/571
- [ ] https://github.com/MicrosoftDocs/WSL/pull/2043
- [ ] https://github.com/MicrosoftDocs/WSL/issues/2045
- [ ] https://github.com/MicrosoftDocs/WSL/issues/2048
- [ ] https://github.com/MicrosoftDocs/WSL/pull/2033
- [ ] https://github.com/MicrosoftDocs/WSL/pull/2040
```

**Comment by mattwojo** [comment]
I'm not sure what you're identifying as an issue here.
